# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/s1734325/SHP/PET-material

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/s1734325/SHP/PET-material

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s1734325/SHP/PET-material/CMakeFiles /home/s1734325/SHP/PET-material/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/s1734325/SHP/PET-material/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Basic_exe

# Build rule for target.
Basic_exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Basic_exe
.PHONY : Basic_exe

# fast build rule for target.
Basic_exe/fast:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/build
.PHONY : Basic_exe/fast

BasicPET.o: BasicPET.cc.o

.PHONY : BasicPET.o

# target to build an object file
BasicPET.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/BasicPET.cc.o
.PHONY : BasicPET.cc.o

BasicPET.i: BasicPET.cc.i

.PHONY : BasicPET.i

# target to preprocess a source file
BasicPET.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/BasicPET.cc.i
.PHONY : BasicPET.cc.i

BasicPET.s: BasicPET.cc.s

.PHONY : BasicPET.s

# target to generate assembly for a file
BasicPET.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/BasicPET.cc.s
.PHONY : BasicPET.cc.s

src/BasicActionInitialization.o: src/BasicActionInitialization.cc.o

.PHONY : src/BasicActionInitialization.o

# target to build an object file
src/BasicActionInitialization.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicActionInitialization.cc.o
.PHONY : src/BasicActionInitialization.cc.o

src/BasicActionInitialization.i: src/BasicActionInitialization.cc.i

.PHONY : src/BasicActionInitialization.i

# target to preprocess a source file
src/BasicActionInitialization.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicActionInitialization.cc.i
.PHONY : src/BasicActionInitialization.cc.i

src/BasicActionInitialization.s: src/BasicActionInitialization.cc.s

.PHONY : src/BasicActionInitialization.s

# target to generate assembly for a file
src/BasicActionInitialization.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicActionInitialization.cc.s
.PHONY : src/BasicActionInitialization.cc.s

src/BasicDetectorConstruction.o: src/BasicDetectorConstruction.cc.o

.PHONY : src/BasicDetectorConstruction.o

# target to build an object file
src/BasicDetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicDetectorConstruction.cc.o
.PHONY : src/BasicDetectorConstruction.cc.o

src/BasicDetectorConstruction.i: src/BasicDetectorConstruction.cc.i

.PHONY : src/BasicDetectorConstruction.i

# target to preprocess a source file
src/BasicDetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicDetectorConstruction.cc.i
.PHONY : src/BasicDetectorConstruction.cc.i

src/BasicDetectorConstruction.s: src/BasicDetectorConstruction.cc.s

.PHONY : src/BasicDetectorConstruction.s

# target to generate assembly for a file
src/BasicDetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicDetectorConstruction.cc.s
.PHONY : src/BasicDetectorConstruction.cc.s

src/BasicEventAction.o: src/BasicEventAction.cc.o

.PHONY : src/BasicEventAction.o

# target to build an object file
src/BasicEventAction.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicEventAction.cc.o
.PHONY : src/BasicEventAction.cc.o

src/BasicEventAction.i: src/BasicEventAction.cc.i

.PHONY : src/BasicEventAction.i

# target to preprocess a source file
src/BasicEventAction.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicEventAction.cc.i
.PHONY : src/BasicEventAction.cc.i

src/BasicEventAction.s: src/BasicEventAction.cc.s

.PHONY : src/BasicEventAction.s

# target to generate assembly for a file
src/BasicEventAction.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicEventAction.cc.s
.PHONY : src/BasicEventAction.cc.s

src/BasicPETHit.o: src/BasicPETHit.cc.o

.PHONY : src/BasicPETHit.o

# target to build an object file
src/BasicPETHit.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETHit.cc.o
.PHONY : src/BasicPETHit.cc.o

src/BasicPETHit.i: src/BasicPETHit.cc.i

.PHONY : src/BasicPETHit.i

# target to preprocess a source file
src/BasicPETHit.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETHit.cc.i
.PHONY : src/BasicPETHit.cc.i

src/BasicPETHit.s: src/BasicPETHit.cc.s

.PHONY : src/BasicPETHit.s

# target to generate assembly for a file
src/BasicPETHit.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETHit.cc.s
.PHONY : src/BasicPETHit.cc.s

src/BasicPETSD.o: src/BasicPETSD.cc.o

.PHONY : src/BasicPETSD.o

# target to build an object file
src/BasicPETSD.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETSD.cc.o
.PHONY : src/BasicPETSD.cc.o

src/BasicPETSD.i: src/BasicPETSD.cc.i

.PHONY : src/BasicPETSD.i

# target to preprocess a source file
src/BasicPETSD.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETSD.cc.i
.PHONY : src/BasicPETSD.cc.i

src/BasicPETSD.s: src/BasicPETSD.cc.s

.PHONY : src/BasicPETSD.s

# target to generate assembly for a file
src/BasicPETSD.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPETSD.cc.s
.PHONY : src/BasicPETSD.cc.s

src/BasicPhysicsList.o: src/BasicPhysicsList.cc.o

.PHONY : src/BasicPhysicsList.o

# target to build an object file
src/BasicPhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPhysicsList.cc.o
.PHONY : src/BasicPhysicsList.cc.o

src/BasicPhysicsList.i: src/BasicPhysicsList.cc.i

.PHONY : src/BasicPhysicsList.i

# target to preprocess a source file
src/BasicPhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPhysicsList.cc.i
.PHONY : src/BasicPhysicsList.cc.i

src/BasicPhysicsList.s: src/BasicPhysicsList.cc.s

.PHONY : src/BasicPhysicsList.s

# target to generate assembly for a file
src/BasicPhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPhysicsList.cc.s
.PHONY : src/BasicPhysicsList.cc.s

src/BasicPrimaryGeneratorAction.o: src/BasicPrimaryGeneratorAction.cc.o

.PHONY : src/BasicPrimaryGeneratorAction.o

# target to build an object file
src/BasicPrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPrimaryGeneratorAction.cc.o
.PHONY : src/BasicPrimaryGeneratorAction.cc.o

src/BasicPrimaryGeneratorAction.i: src/BasicPrimaryGeneratorAction.cc.i

.PHONY : src/BasicPrimaryGeneratorAction.i

# target to preprocess a source file
src/BasicPrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPrimaryGeneratorAction.cc.i
.PHONY : src/BasicPrimaryGeneratorAction.cc.i

src/BasicPrimaryGeneratorAction.s: src/BasicPrimaryGeneratorAction.cc.s

.PHONY : src/BasicPrimaryGeneratorAction.s

# target to generate assembly for a file
src/BasicPrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicPrimaryGeneratorAction.cc.s
.PHONY : src/BasicPrimaryGeneratorAction.cc.s

src/BasicRunAction.o: src/BasicRunAction.cc.o

.PHONY : src/BasicRunAction.o

# target to build an object file
src/BasicRunAction.cc.o:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicRunAction.cc.o
.PHONY : src/BasicRunAction.cc.o

src/BasicRunAction.i: src/BasicRunAction.cc.i

.PHONY : src/BasicRunAction.i

# target to preprocess a source file
src/BasicRunAction.cc.i:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicRunAction.cc.i
.PHONY : src/BasicRunAction.cc.i

src/BasicRunAction.s: src/BasicRunAction.cc.s

.PHONY : src/BasicRunAction.s

# target to generate assembly for a file
src/BasicRunAction.cc.s:
	$(MAKE) -f CMakeFiles/Basic_exe.dir/build.make CMakeFiles/Basic_exe.dir/src/BasicRunAction.cc.s
.PHONY : src/BasicRunAction.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Basic_exe"
	@echo "... BasicPET.o"
	@echo "... BasicPET.i"
	@echo "... BasicPET.s"
	@echo "... src/BasicActionInitialization.o"
	@echo "... src/BasicActionInitialization.i"
	@echo "... src/BasicActionInitialization.s"
	@echo "... src/BasicDetectorConstruction.o"
	@echo "... src/BasicDetectorConstruction.i"
	@echo "... src/BasicDetectorConstruction.s"
	@echo "... src/BasicEventAction.o"
	@echo "... src/BasicEventAction.i"
	@echo "... src/BasicEventAction.s"
	@echo "... src/BasicPETHit.o"
	@echo "... src/BasicPETHit.i"
	@echo "... src/BasicPETHit.s"
	@echo "... src/BasicPETSD.o"
	@echo "... src/BasicPETSD.i"
	@echo "... src/BasicPETSD.s"
	@echo "... src/BasicPhysicsList.o"
	@echo "... src/BasicPhysicsList.i"
	@echo "... src/BasicPhysicsList.s"
	@echo "... src/BasicPrimaryGeneratorAction.o"
	@echo "... src/BasicPrimaryGeneratorAction.i"
	@echo "... src/BasicPrimaryGeneratorAction.s"
	@echo "... src/BasicRunAction.o"
	@echo "... src/BasicRunAction.i"
	@echo "... src/BasicRunAction.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

